# Generated by Django 5.0.7 on 2024-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_new_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='like_new',
            field=models.BooleanField(default=False),
        ),
    ]
