# Generated by Django 5.0.7 on 2024-07-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
